# server port Setting
server:
  port: 60002
#  port: 80

# Context Name Setting
#  servlet:
#    context-path: /demo9

spring:
  application:
    name: greenprojectB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false

  # Database Setting(datasource setting)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenprojectB
    username: root
    password: 0519

  # JPA Setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # create, update, none, create-drop....
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true    # sql view
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # File Upload MaxSize Setting
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 30MB


